### PR TITLE
Refactor of Jupyter Main Site

### PR DESCRIPTION
**Pull request by cameronoelsen**
After looking through the HTML & CSS of the Jupyter main site, I found that there was a lot of CSS that was confusing, not labeled correctly or not even used. I also refactored the sections of the site to be reusable so anyone can make beautiful pages :) 

There are now also comments throughout the CSS to explain what each specific class does and where it is used inside the website.

Lastly, I took another pass at the resources page to standardize the resource icons that are being used.

### CODE REVIEW

**Comment by cameronoelsen** [comment]
@willingc Here is the PR :)

**Comment by cameronoelsen** [comment]
@willingc I did that and also changed the name of the file but it still seems to be thinking there is a conflict with the calendar icon...

**Comment by willingc** [comment]
@Carreau @rgbkrk @cameronoelsen I thought I fixed the merge conflict with the svg but the site isn't rendering correctly :( Do any of you see the error?

**Comment by willingc** [comment]
Meh. Nevermind. I looks fine in Chrome Incognito window so my browser must not have completely cleared the cache. Please take a look and confirm that it looks okay on your systems. Thanks!

**Comment by willingc** [comment]
@Ruv7 FYI. First set of Cameron's cleanup has been merged.

**Comment by charnpreetsingh185** [comment]
@cameronoelsen Looks like we lost some icons. Viewing this on Safari.
screen shot 2016-10-31 at 1 27 55 pm

**Comment by willingc** [comment]
@charnpreetsingh185 Perhaps clear your cache and reload.  It looks fine on El Capitan 10.11.6 and Safari below. Unless it's a Sierra thing. P.S. Sorry for forgetting to copy you above. I did mention you in the PR commit :smile:

screen shot 2016-10-31 at 13 35 35

**Comment by charnpreetsingh185** [comment]
@willingc No worries! I tried it on Chrome 54 and the problem still persists. MacOS Sierra 10.12.1

Inspecting the element shows that the image is there but not rendering properly.

**Comment by willingc** [comment]
Ugh...Sierra. @charnpreetsingh185 Did you try loading in an Incognito window?

**Comment by charnpreetsingh185** [comment]
@willingc Yes I tried that but the issue still persists.

**Comment by willingc** [comment]
Thanks Charnpreet. Would you mind opening an inssue on this and include whatever output or  screenshots you think  would be valuable? Thanks!

**Comment by charnpreetsingh185** [comment]
@willingc Found the issue with @cameronoelsen! We were using a class called `sponsor-logo` that coincidentally adblock plus was also using causing adblock to block the image on the page.

**Comment by willingc** [comment]
Hey @charnpreetsingh185 and @cameronoelsen, Fantastic troubleshooting :cake: :cookie: Very impressive 👍

**Comment by cameronoelsen** [comment]
@willingc It's ready to merge in the jupyter.github.io repo :) Thanks btw

**Pull request merged**
