### PR TITLE
Get rid of sepia tint on mugshots

### PR DESCRIPTION
**Pull request by takluyver**
I don't think it looks good

### CODE REVIEW

**Comment by rgbkrk** [comment]
I liked sepia, willing to try this.

**Comment by takluyver** [comment]
I'm open to experimenting with different ways to do hover effects, but the sepia tint on a bunch of differently coloured photos didn't work for me.

**Comment by rgbkrk** [comment]
I think we should use a rosy color next.

**Comment by takluyver** [comment]
:-)

**Pull request merged**
