### PR TITLE
Added lazy loading in /about page

### LINKED ISSUE #532: Utilize native lazy-loading to reduce initial page load
As [described by Google](https://web.dev/browser-level-image-lazy-loading/), native lazy loading is now support in Chrome and Firefox. It is an easy tool to increase speed on pages with lots of images.

The homepage and the about page each bring in dozens of logos and images below the initial viewport. These images are ideal candidates for lazy loading. Let's implement the feature.

### PR DESCRIPTION
**Pull request by dn-flixee**
## Added Lazy Loading in About Page
* Closes #532

### CODE REVIEW

**Comment by palewire** [comment]
I'm unfamiliar with the changes here to the Gemfile. What do these packages do?

**Comment by dn-flixee** [comment]
I am currently on a windows machine, so to make it work on my local. I added those packages. I have mentioned the stackoverflow link in the comment.

**Comment by palewire** [comment]
Okay. That's fine for your setup if it works but we should leave it out of this pull request since it's not directly related to your patch.

**Comment by dn-flixee** [comment]
I have made a new commit. Sorry I didn't know that we need to remove dependencies.

**Comment by palewire** [comment]
Great. Thanks. Another thing now: I don't see your edits to the about.md page in the pull request. Are you sure you committed and pushed your changes? Check the "Files changed" tab at the top here and you'll see what I mean.

**Comment by dn-flixee** [comment]
Hi @palewire. I tried to fix the issue. But it got closed somehow. Can you please guide me ?

**Comment by choldgraf** [comment]
@dn-flixee want to just try opening a new pull request, with only the `/about` changes in there?

**Comment by dn-flixee** [comment]
> @dn-flixee want to just try opening a new pull request, with only the `/about` changes in there?

The about.html file is under _site which is gitignored and hence my changes are not being tracked by git.

**Comment by palewire** [comment]
Gotcha. The _site folder is the built site after all of our code is run. That's the result of your work, not where you work. The file you want to edit is /about.md here https://github.com/jupyter/jupyter.github.io/blob/master/about.md

**Comment by dn-flixee** [comment]
I don't know, how to integrate lazy loading to a md file. I didn't get the part where you have to dynamically add lazy loading to the html. I worked on the statically generated about.html and didn't noticed that it is dynamically getting created and being gitignored. @palewire

**Comment by palewire** [comment]
The md file is an HTML template that allows for some looping and other programming tricks. You'll want to find the line there that outputs the HTML you'd like to change and edit it there. 

Let's give you a simple one to change. See if you can add the `loading="lazy"` attribute to the tags here. Let's limit your patch to that one change. https://github.com/jupyter/jupyter.github.io/blob/master/_includes/cards.html#L9

**Comment by dn-flixee** [comment]
Can you please open this issue again @palewire  ? Thanks!

**Pull request closed without merging**
