### PR TITLE
create community calendar link fixes #117

### LINKED ISSUE #117: Add events calendar to community page
The calendar: https://calendar.google.com/calendar/embed?src=p51j0ac1iccmj44tae12hq4dk0%40group.calendar.google.com

should probably be embedded in or linked from the community page

### PR DESCRIPTION
**Pull request by go-bears**
Resolves issue #117 :  create link to Jupyter events calendar, add calendar icon, on community.html page

### CODE REVIEW

**Comment by Carreau** [comment]
Thanks ! That's great ! 

Where did you get the calendar icon?  there seem to be some weird thing with it though, like the SVG look like it has an embedded PNG in it.

Or did you do it yourself using inkscape ? If so OS X is known to have this issue when copy and pasting.

**Comment by go-bears** [comment]
Hi I can't remember where I downloaded the link from. I downloaded the file and manipulated it with Inkscape, but on a machine running Ubuntu. I'll take a look at the graphic image again.  Thanks for letting me know about the issue!

**Comment by rgbkrk** [comment]
We can probably just merge this as is and then iterate with another PR. The entire SVG is only 14KB.

**Comment by Carreau** [comment]
Sure, it was also a question of file licence, and just to be sure the
base64 was not something else than a PNG.

**Comment by go-bears** [comment]
Ah! thanks for letting me know.  I got the image from here: https://www.iconfinder.com/icons/115762/calendar_date_event_month_icon
And it has a Creative Commons (Attribution 3.0 Unported) License 

    Share — copy and redistribute the material in any medium or format
    Adapt — remix, transform, and build upon the material
    for any purpose, even commercially.

    The licensor cannot revoke these freedoms as long as you follow the license terms.

I guess attribution would be Designmodo? But I'm not sure where to put that info?

**Comment by Carreau** [comment]
I would put that in a comment in the html source, or in a file `assets/calendar-icon-credits.txt`. Thoughts ?

**Comment by Carreau** [comment]
@go-bears I sent you a PR that should fix the SVG.

**Pull request merged**
