### PR TITLE
Fix the problem with widgets content tab mis-alignement

### LINKED ISSUE #364: CSS related bugs in the widgets page
Hi,

#### Problem 1
I encountered another CSS related bug. The widgets page loads as expected in the beginner, and later the RequireJS library starts loading the resources for the individual widgets. It seems like the CSS code that comes with one of these widgets overwrite the website's CSS code. As a result, the navigation bar changes and the Jupyter logo in the navigation bar get cropped:

ezgif com-video-to-gif

I tried loading the `logo-nav.css` code at the end of this page, and it solved the problem I mentioned above. I wonder if that is an acceptable way for you to solve it.

#### Problem 2
Additionally,  the height of the tabs on the left doesn't scale based on the contents of the widget. As a result, the contents of the widgets spill to the left side of the page:

Screen Shot 2020-05-10 at 11 09 45 PM

I couldn't find a solution to solve the spilling problem yet.

### PR DESCRIPTION
**Pull request by krassowski**
Fixes #364 problem 2 (problem 1 was already fixed).

`display: flex` is magic, we need more of it.

### CODE REVIEW

**Comment by krassowski** [comment]
No deploy preview on this one? :(

**Comment by choldgraf** [comment]
looks like there was an error in the netlify build? I don't believe I have access to re-trigger though. @Carreau any chance you have access?

**Comment by choldgraf** [comment]
still an error, the netlify page suggests this is @Carreau's account so I guess we need to wait for him to debug

**Comment by krassowski** [comment]
It seems the netlify integration does not kick in after close/reopen but force pushes still work to re-trigger.

**Comment by krassowski** [comment]
Left before, right after.

Screenshot from 2021-06-21 16-21-50

**Review by choldgraf — APPROVED** [review]
ah looks great - I'll merge in a day or two unless somebody suggests otherwise

**Comment by choldgraf** [comment]
thanks :-)

**Pull request merged**
