### PR TITLE
Added logo and Community tests

### PR DESCRIPTION
**Pull request by cameronoelsen**
-Per request from Sharpe Engineering, we have added the N-site LLC logo
to the company showcase on the front landing page
-Added images onto the site for me to start testing a new section for
the about page. Once these are on the site, it will be much easier for
me to design a D3 visualization that we will be hosting.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Thanks @Carreau for merging this!

**Comment by Carreau** [comment]
You should be able to make the circle as d3 circle with a text attribute, but if it's easier with PNG it's fine with me.

**Comment by Carreau** [comment]
> Thanks @Carreau for merging this!

Where you watching the PR ? it took you 13 sec to respond !

**Comment by cameronoelsen** [comment]
@Carreau Brian was going to merge it like a second before you and you beat him to it :tada:

**Comment by ellisonbg** [comment]
@Carreau - yeah I was about to click the button :)

If you are in the merging mood - maybe this one:

https://github.com/ipython/ipython-website/pull/100



On Fri, Sep 11, 2015 at 2:52 PM, Cameron Oelsen <notifications@github.com>
wrote:

> @Carreau <https://github.com/Carreau> Brian was going to merge it like a
> second before you and you beat him to it [image: :tada:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/pull/37#issuecomment-139669630>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
