### PR TITLE
new-mail-education-icon

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Fixes issue on education mailing list icon.

The new icon is a bit simpler: only the middle part, but bigger.

edu

Here is the old icon:

edu-old

I had trouble recognizing the graduation cap in the drawer :)

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@willingc @ellisonbg any comment on that one?

**Comment by willingc** [comment]
@SylvainCorlay This seems like a reasonable change to merge. I too think it's difficult to see that it's a graduation cap in the mailbox. I would also recommend editing the text for the item to remove the repeated use of Jupyter:

Jupyter in Education Mailing List

A Google Group for general ~~Jupyter~~ discussions of Jupyter's use in education.

cc @ellisonbg

**Comment by SylvainCorlay** [comment]
merge?

**Comment by willingc** [comment]
Thanks @SylvainCorlay.

**Pull request merged**
