### PR TITLE
Updated Company Logos

### PR DESCRIPTION
**Pull request by cameronoelsen**
-Added northwestern to company front page in response to request

### CODE REVIEW

**Comment by rgbkrk** [comment]
Uh... Is this the same as #35?

**Comment by Carreau** [comment]
Yes, seem really similar. 

Usually when people do PR it would be nice if you think their commit it not perfect to continue work on top of theirs, so that at least they get into the history. Unless it's really complicated. 

Especially when people took time to work on that, it is always a reward to get things in.

**Comment by nicktimko** [comment]
Minor quibble: you're using the logo in a manner that's not conforming with the school's [guidelines for use](https://web.archive.org/web/20140723170317/http://www.northwestern.edu/univ-relations/identity-system/guidelines.html).

> The logo is a single element. The seal and the words "Northwestern University" should always appear together.

 #35 includes the seal/title together

**Comment by cameronoelsen** [comment]
@nicktimko will fix now

**Comment by nicktimko** [comment]
The link was also broken; missing a `:` in `http//...`

**Comment by ellisonbg** [comment]
Thanks for the clarification!

On Tue, Sep 15, 2015 at 3:39 PM, Nick Timkovich <notifications@github.com>
wrote:

> The link was also broken; missing a : in http//...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/pull/36#issuecomment-140568574>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
