### PR TITLE
all URLs now https

### PR DESCRIPTION
**Pull request by choldgraf**
in #308 @Carreau noted that a bunch of links in the repo weren't https...this PR (kind of dumbly) updates a bunch of links to use https instead of http. Let's see if the website still works when it's built :-)

### CODE REVIEW

**Comment by Carreau** [comment]
Dear old friend `sed -i`.

That does seem to completely fuck up the rendering though:
screen shot 2018-09-26 at 15 39 41

**Comment by choldgraf** [comment]
hehe ok, I will look at this again once my plane has landed and try to not-totally-fuck-it-up :-)

**Comment by Carreau** [comment]
It may not be your fault it might be things like doctype/DTD that dont' like https. Or just netlify that fucks up.

**Comment by choldgraf** [comment]
cc @Carreau in case you aren't watching this one anymore :-)

**Comment by minrk** [comment]
Looks fine now. Thanks @choldgraf!

**Pull request merged**
