### PR TITLE
Removed colors from NASA logo

### PR DESCRIPTION
**Pull request by ehsteve**
Forgot to do that. Sorry.

### CODE REVIEW

**Comment by minrk** [comment]
I'm not sure if this is something you can do, but is it possible for the blue and the red to be different grays?

**Comment by ehsteve** [comment]
I can do that but none of the other logos have more than one level of grey so I thought that that was the style you were going for. Do you have a preference for the other gray color (#??????).

**Comment by minrk** [comment]
Good point, though this is the first logo where there are two colors overlapping with no border, so it looks a bit funny. I found `#888888` for the red to work okay. Perhaps @cameronoelsen should weigh in, though.

**Comment by ellisonbg** [comment]
Please use a single grey that matches the other logos on that area of the
page. Can we revert until the grey gets fixed? It really stands out in an
inappropriate way on the live page.

On Thu, Oct 29, 2015 at 9:24 AM, Min RK <notifications@github.com> wrote:

> Good point, though this is the first logo where there are two colors
> overlapping with no border, so it looks a bit funny. I found #888888 for
> the red to work okay. Perhaps @cameronoelsen
> <https://github.com/cameronoelsen> should weigh in, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/pull/62#issuecomment-152178021>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
@ellisonbg it's a single gray now that matches everything else; that's what this PR fixes (and deployed as-is to fix the color issue on the website). The NASA logo is unique in that it's the only logo so far where two overlapping shapes are distinguished *only* by color. For that reason, I think it should be two-tone.

**Comment by ellisonbg** [comment]
OK, thanks for merging this. @cameronoelsen can you look at the NASA logo
and see if you can can make a 3 tone version of this that preserves the
original relative weighting of the white/blue/red. My concern is that most
organizations do now allow third parties to modify the logo when it is used
like this. I am fine with a subtle multi-tone grey that matches the visual
style of the other logos on the page, and that preserves the look of the
original logo.

On Thu, Oct 29, 2015 at 9:35 AM, Min RK <notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> it's a single gray now that
> matches everything else; that's what this PR fixes (and deployed as-is to
> fix the color issue on the website). The NASA logo is unique in that it's
> the only logo so far where two overlapping shapes are distinguished *only*
> by color. For that reason, I think it should be two-tone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/pull/62#issuecomment-152180405>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
That's another good point, and the single-gray looks less weird when it's small on Jupyter.org. Looking at the large image in reviewing this PR, it definitely doesn't look right, but I'm okay leaving it as-is given its small target context.

You can find [other examples](https://www.google.com/search?q=nasa+monochrome+logo&espv=2&biw=1137&bih=1082&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMIt4no-efnyAIVgR0sCh3nowaI#tbm=isch&q=nasa+monochrome+logo+site:nasa.gov) of monochrome treatments of this logo, some of which use strokes and keep it one-bit, others use an extra gray.

**Comment by ehsteve** [comment]
There exists an official style guide for the [NASA meatball](http://sservi.nasa.gov/wp-content/uploads/2011/10/NASA_Style_Guide_v2.1.pdf) which more monochrome but it uses black for blue and grey for the red. See page 8.

**Comment by ehsteve** [comment]
I think the main issue is that though changing organizations logos so that they have a common style as you have done here looks nice but fundamentally you are CHANGING their logos without their permission. Of course, it is unlikely that they will come along and complain (unless you ask for permission to change the logo).

**Comment by ellisonbg** [comment]
Thanks, this guide will help Cameron to come up with a a good style. I
don't think we want to use black (will still stick out too much) that guide
has the needed information to make a nice 3 grey design that follows their
guidelines.

On Thu, Oct 29, 2015 at 10:37 AM, Steven Christe <notifications@github.com>
wrote:

> I think the main issue is that though changing organizations logos so that
> they have a common style as you have done here looks nice but fundamentally
> you are CHANGING their logos without their permission. Of course, it is
> unlikely that they will come along and complain (unless you ask for
> permission to change the logo).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/pull/62#issuecomment-152199943>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cameronoelsen** [comment]
I'm on it!

**Comment by cameronoelsen** [comment]
@ellisonbg #63 should fix it up! If there are any suggestions to that I can make the changes pretty quickly so we can push to the live site!

**Comment by willingc** [comment]
@cameronoelsen Nicely done :surfer: :computer: :art:

**Pull request merged**
