### PR TITLE
Cut widgets from nav

### PR DESCRIPTION
**Pull request by palewire**
As we continue to hone the homepage as a result of the discussion in #433, I propose this edit.

In my view, the nav, which has very limited space to work with, should be restricted to highest level metadata about the project. In my view, the widgets pages is not at the top level of the hierarchy. So I suggest removing it from this position.

### CODE REVIEW

**Comment by krassowski** [comment]
What if we had a dropdown with "More" instead of removing bits and pieces? I think that placement in the navbar facilitates discoverability - if it is not there many users won't see it. I really think that having "More" would be useful.

**Comment by palewire** [comment]
Something like that could be a good future addition. Good to remember that, right now, widgets is in the nav but the /binder and /conduct pages are not. Hard to justify having this one up there and not those. And there clearly isn't space to include them all.

My feeling is that trimming it is a good incremental practice before building it back up, which is why I am submitting this small edit alone.

**Comment by choldgraf** [comment]
If we remove `widgets` is there any other place where people can get to that page?

I think it's OK to remove them now, and I agree that something like a `projects` dropdown is the right way to do it. As long as we collect a list of the projects that will need to be there so that we don't lose track, I'm +1 on it

**Comment by palewire** [comment]
It is not listed anywhere else. Though, neither are the /conduct and the /binder pages, which have long been orphans.

My take is we should continue to prune this nav down to a strong foundation, then look to build it back up after we've settled on what won't make the top line cut.

**Comment by choldgraf** [comment]
+1 from me - I just wanna make sure keep track of the orphans somewhere, so that it doesn't become an information silo!

**Comment by palewire** [comment]
@choldgraf, I made up a ticket where I tried to record the scope of the problem and open room for discussion. https://github.com/jupyter/jupyter.github.io/issues/529

**Comment by SylvainCorlay** [comment]
No problem making it a temporary orphan as long as we come up with another easy way to find this content eventually. Let's improve navigation.

**Review by choldgraf — APPROVED** [review]
Ok we have a few approves, a plan for how to add this content back in, and an issue to track it. This LGTM !

**Pull request merged**
