### PR TITLE
Tidy homepage layout and CSS

### PR DESCRIPTION
**Pull request by palewire**
This path refactors the homepage layout. It includes the following changes:
- Creating a new include component for the "showcase" homepage module
- Added a SCSS component to style all homepage elements
- Removed crufty HTML `div` tags that aren't needed
- Reworked elements to use flexbox layouts
- Attempted to smooth out inconsistencies in padding, font-size and other settings across elements, fixing #510
- Switched the showcase module to left alignment on mobile, fixing #459 
- Removed crufty SVG elements from the open standards section

Other than what's described above, the page should look virtually the same as before.

### CODE REVIEW

**Review by choldgraf — COMMENTED** [review]
I don't have bandwidth to go through the changes with a fine-toothed comb, but looking at the structure of the HTML/CSS changes here, it looks pretty reasonable to me.

I did find a regression in the "open standards for interactive computing" section at the bottom - the content flows off the screen to the right on mobile views:

image

If we can fix this and confirm there are no other visual regressions on wide/mobile, I'm +1 on this

**Comment by palewire** [comment]
What browser width are you seeing that at? I don't see it in my mobile testing.

Screenshot from 2022-01-09 08-28-25

Though it does seem clear those boxes need to wrap at a wider width than where they are currently. I will patch that.

**Comment by palewire** [comment]
That's been done. 767px is now the break to the stacked "column" flex layout.

**Review by choldgraf — APPROVED** [review]
Your latest changes fixed the box overflow problem, so I'm +1 on this one, thanks for the refactor, this feels a lot cleaner!

**Pull request merged**
