### PR TITLE
New Documentation Experience

### PR DESCRIPTION
**Pull request by cameronoelsen**
Added classes for specifying the color of the navbar and the header instead of defaulting to a specific color. 

This is mainly preparing for the new documentation page that is in progress, but this theming will be helpful for others in the future in regards to building a page with customization. Nothing looks different aesthetically on the frontend of the site.

### CODE REVIEW

**Comment by Carreau** [comment]
Your  assets/documentation/ipython-block-placeholder.png has a border of transparent pixel, I dont' know if this is on purpose.

**Comment by willingc** [comment]
@cameronoelsen @charnpreet This is looking very good. 

I did find on Safari in a narrow width that the labels are overwriting their borders.
screen shot 2017-05-04 at 9 58 34 am
screen shot 2017-05-04 at 9 58 48 am

We'll need to update some of the links in the dropdowns but we could do that in a separate PR (which would probably be simpler).

**Comment by willingc** [comment]
Here's after the fix :sunny:
screen shot 2017-05-04 at 10 55 07 am

**Comment by cameronoelsen** [comment]
This PR has been sitting for a while, is it good to assume that we can merge it? Just want to push forward the new documentation themes :)

**Comment by willingc** [comment]
@cameronoelsen I'm going to go ahead and merge this. We can iterate any breakages that might happen. Thanks. cc/ @ellisonbg @charnpreetsingh

**Comment by rgbkrk** [comment]
Sweet, glad we've got some top level documentation navigation. Thank you all!

**Pull request merged**
