### PR TITLE
Add banner for jupytercon CFP

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Ping @jasongrout

**Comment by labarba** [comment]
This is OK with me (we discussed with Sylvain on Slack and tweaked final look).

**Comment by SylvainCorlay** [comment]
Thanks. Since the CFP is open, and this is merely a slightly tweaked version of the 2018 JupyterCon banner, I will go ahead and merge. People intersted in iterating on this, feel free to comment more here.

**Comment by Carreau** [comment]
Thanks @SylvainCorlay !

**Pull request merged**
