### PR TITLE
Add Northwestern Univ to list of users

### PR DESCRIPTION
**Pull request by nicktimko**
Our lab at Northwestern has been heavily proselytizing use of IPython/Jupyter and has run several bootcamps, reaching nearly 1000 users in total on campus.  Each iteration of the bootcamp becomes increasingly centered around notebooks as a way to teach programming and communicate research.

Here's a [press release](http://www.tgs.northwestern.edu/resources-for/postdocs/news-events/stories/2014/northwesterns-big-data-initiative.html) from our bootcamp last year when we did about 50-75% of it in notebooks. The one we're doing this week is basically 100% notebook driven.

### CODE REVIEW

**Comment by nicktimko** [comment]
Here's a [press release](http://www.tgs.northwestern.edu/resources-for/postdocs/news-events/stories/2014/northwesterns-big-data-initiative.html) from our bootcamp last year when we did about 50-75% of it in notebooks. The one we're doing this week is basically 100% notebook driven.

**Comment by rgbkrk** [comment]
Certainly looks good to me. Ping @cameronoelsen.

**Comment by ellisonbg** [comment]
Will talk to Cameron about this tomorrow. But +1 from me. Thanks Nick!

On Mon, Sep 7, 2015 at 7:09 PM, Kyle Kelley <notifications@github.com>
wrote:

> Certainly looks good to me. Ping @cameronoelsen
> <https://github.com/cameronoelsen>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/pull/35#issuecomment-138409576>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cameronoelsen** [comment]
This was merged

**Comment by Carreau** [comment]
reopen until we fix the issue raise in #36.

**Comment by nicktimko** [comment]
Updated it with master (is that a rebase? I dunno...doing this mostly to learn how to do a PR)

**Comment by Carreau** [comment]
> is that a rebase? I dunno...doing this mostly to learn how to do a PR

Well that was a merge, but it's fine too. Thanks, merging, and you are doing great with git !

**Comment by Carreau** [comment]
it should take a couple of minutes to be on the website itself.

**Pull request merged**
