### PR TITLE
Added Perspective to list of widgets, and added gif to assets.

### PR DESCRIPTION
**Pull request by ruthussanketh**

### CODE REVIEW

**Comment by timkpaine** [comment]
name is just "perspective", thanks!

**Comment by ruthussanketh** [comment]
Done! @timkpaine

**Comment by timkpaine** [comment]
would it make sense to use this as the gif https://camo.githubusercontent.com/f69d1132e2984e2a97209fc21520e9812c464873/68747470733a2f2f70657273706563746976652e66696e6f732e6f72672f696d672f64656d6f5f736d616c6c2e676966

**Comment by ruthussanketh** [comment]
Yes, I've added it in the image section. Does it look better now?

**Comment by timkpaine** [comment]
it should probably be copied locally into `assets/perspective.gif`

**Comment by ruthussanketh** [comment]
I'm not sure if what I've done now is right. Does it look okay? Added the gif as .gif in assets.

**Comment by timkpaine** [comment]
yep looks good!

@blink1073 does this look ok?

**Comment by timkpaine** [comment]
@blink1073 and @ruthussanketh thanks!

**Pull request merged**
