### PR TITLE
Add Kotlin to the Try page

### PR DESCRIPTION
**Pull request by ileasile**
Kotlin Jupyter kernel is mature enough to be mentioned on this page too.
https://github.com/Kotlin/kotlin-jupyter

Will make it not-draft after text and logo reconciliation.

### CODE REVIEW

**Comment by afshin** [comment]
@ileasile, is this still a draft? No rush if it is, I am just checking to confirm.

**Comment by ileasile** [comment]
@afshin well, I found one appropriate notebook for example. So, now it's not draft

**Review by afshin — APPROVED** [review]

**Comment by Carreau** [comment]
Thanks !

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/governance-office-hours-meeting-minutes/1480/170

**Pull request merged**
