### PR TITLE
Update try to reflect JL is ready

### PR DESCRIPTION
**Pull request by saulshanabrook**

### CODE REVIEW

**Comment by saulshanabrook** [comment]
@ivanov Sounds good, I moved the order back to the original

**Comment by saulshanabrook** [comment]
@afshin had merged this changes in already (https://github.com/jupyter/jupyter.github.io/pull/342), so now this PR reverts back the order to the previous.

**Comment by afshin** [comment]
Thanks @saulshanabrook! Superseded by https://github.com/jupyter/jupyter.github.io/pull/342

**Comment by saulshanabrook** [comment]
@afshin Could you reopen this? It adds some changes suggested by @ivanov on top of the commit that you already applied.

**Comment by afshin** [comment]
Sorry about that! You may need to rebase against `master`. Two PRs have gone in now.

**Comment by jasongrout** [comment]
> The JupyterLab Lorenz Demo notebook is not the right place to send people as a primary resource without explaining notebooks at all.

*very* good point. The JLab demo binder is about introducing someone to jlab, assuming they are already fairly comfortable with the classic notebook.

Perhaps we can copy those good introductory notebooks to the jlab demo repo?

**Comment by jasongrout** [comment]
Merging to put things back the way they were with the order until we can make the jlab demo more friendly for first-time users.

**Pull request merged**
