### PR TITLE
Add nglview example to widget page

### PR DESCRIPTION
**Pull request by hainm**
Hi,

it would be great if we (cc @arose) can show an example of [nglview](https://github.com/arose/nglview) in jupyter widget page.
Let me know what you think or I need do to something else. thanks and cheers.

nglview-jupyter

PS: In case you're curious, here is the data to reproduce the example:
https://github.com/hainm/notebook-nglview/tree/master/membrane

### CODE REVIEW

**Comment by hainm** [comment]
it's been a week. Is there any admin can comment on this case? thanks 
cc @jasongrout @SylvainCorlay

**Comment by SylvainCorlay** [comment]
Sorry I missed it. I will review it today!

**Comment by SylvainCorlay** [comment]
This looks good to me. @Carreau are you ok with pressing the green button?

**Comment by Carreau** [comment]
> This looks good to me. @ellisonbg @Carreau are you ok with pressing the green button?

I will, but then I'll be a a plane so the responsibility is on @ellisonbg  or @SylvainCorlay  :-)

**Comment by hainm** [comment]
thank you all.

**Pull request merged**
