### PR TITLE
Accessibility fixes to buttons, footer and blue cards

### PR DESCRIPTION
**Pull request by palewire**
Updated accessibility fixes to the site, as raised by Lighthouse, and as prescribed by @isabela-pf in #435.

### CODE REVIEW

**Comment by palewire** [comment]
These changes raise the Lighthouse accessibility score to 100 in my browser testing.

**Comment by isabela-pf** [comment]
Looks good to me, and good to know it's working with Lighthouse as intended! I'll @ someone with write access if this doesn't get attention in the next week.

Thank you so much for being receptive to feedback, I really appreciate it.

**Comment by isabela-pf** [comment]
For records, here are some screen shots from the netlify preview as I'm finding it:
Jupyter.org homepage with a text shadow on buttons.
Jupyter.org footer with a darker grey.
Jupyter.org documentation page with darker blue sections.

**Review by isabela-pf — APPROVED** [review]

**Comment by Carreau** [comment]
@isabela-pf I gave you write access, I thought you already had it.

**Pull request merged**
