### PR TITLE
add minimal IPython/Jupyter info to Jupyter.org

### PR DESCRIPTION
**Pull request by minrk**
in preparation for IPython 3.0.

Adds simple bullet illustration of what's Jupyter and what's IPython and a brief paragraph about IPython 3.0 and the future.

also use the real Jupyter logo while we are at it, and stop using the Minion font that no longer makes sense with the new logo.

coLaboratory link in the footer is also removed

preview at http://minrk.github.io/jupyter.github.io/

### CODE REVIEW

**Comment by minrk** [comment]
ping @ellisonbg, @fperez for what info we want on this page

I presume we will actually deploy a proper website here at some point, but this should help people have some idea what Jupyter is in the meantime.

**Comment by rgbkrk** [comment]
Looking good!

**Comment by Carreau** [comment]
+1, I think in a subsequennt PR we shoudl add FAQ like "How do I install Jupyte", "Can I try it ?", list of kernels....

**Comment by minrk** [comment]
Yup, we should definitely spend the time to set up a proper website for Jupyter.

**Comment by takluyver** [comment]
Do we want to also use the new favicon while we're at it?

**Comment by Carreau** [comment]
[troll]

I think the white background should have a drop shadow, as in the notebook, to 
convey the "document" meaning. 

I think we should try to user test wether the text should be justified or not. 

And I don't think the abstraction and mental model the users developed using our website are not well defined. 
[/troll]

**Comment by Carreau** [comment]
Sidenote, not trolling; link to google group would be nice.

**Comment by minrk** [comment]
> Do we want to also use the new favicon while we're at it?

Done.

> link to google group would be nice.

Done.

**Comment by Carreau** [comment]
Damned I was going to send you a PR.

**Comment by rgbkrk** [comment]
:shipit:

**Comment by fperez** [comment]
+1. I'm sure we'll do lots more in the future, this is good for now.

**Pull request merged**
