### PR TITLE
Changed JupyterCon Message

### PR DESCRIPTION
**Pull request by tgeorgeux**
Removed call for proposals for a general link to the conference website.

### CODE REVIEW

**Comment by Ruv7** [comment]
Thanks Tim, can you include a screenshot so I can review?

**Comment by Ruv7** [comment]
Text is looking crowded to me. Can you help me see what the header said last year? At the very least the button should read "Learn More" not "Learn More about JupyterCon" it's redundant.

**Comment by jzf2101** [comment]
@Ruv7 just made a change based on your suggestion

**Comment by Ruv7** [comment]
Nevermind, I see last year's - there was much more visual real estate in that one. What's the thought process surrounding not having this message at the very top of the page? Here is the message I suggest for the text above the button, let's keep it simple and stay away from exclamation points, doesn't match the tone of the rest of the page - too jazzy >.< 

Line 1: JupyterCon 2018 
Line 2: August 21 - 25 
Line 3: Learn More button

Also we need to use the following link for tracking purposes: https://conferences.oreilly.com/jupyter/jup-ny?cmp=ex-data-confreg-home-jpny18_pj_site

**Comment by tgeorgeux** [comment]
@Ruv7 we're simultaneously building out the lab header for the page. This will exist below the lab announcement for a few weeks, then we'll switch to the Jupytercon being the primary announcement and Lab existing below. 

I want to do an entire website rebuild over the summer, but that's outside of the scope of this PR. 

Jessica is making requested changes to content.

**Comment by Ruv7** [comment]
Got it @tgeorgeux - looks better. Change the date to the 25th. On our blog announcement we include the Community Sprint Day as the end of the conference not the 24th. https://blog.jupyter.org/jupytercon-2018-nyc-august-21-25-5571d7454d5b

**Comment by Ruv7** [comment]
Looks ok, someone else will need to merge this PR - looks like I don't have permissions anymore.

**Comment by tgeorgeux** [comment]
@willingc Do you know who has the rights to merge on the website?

**Comment by Ruv7** [comment]
If I'm looking at the right thing above @Carreau and @ellisonbg are the code owners.

**Comment by willingc** [comment]
I think that I can press the green Merge button, but will defer to @Carreau and @ellisonbg.

I wonder if now or in the future it would make sense to use the JupyterCon logo for the first line of text and move 2018 down to the date. 

As a straightforward update, this is ready to merge.

**Comment by Ruv7** [comment]
Zero traffic has been generated to date from the jupyter.org home page to Jupytercon website. Either something is broken or the placement/size of the message has affected traffic. Flagging this now and we can discuss further when I have details from the O'Reilly marketing team. Is commenting the appropriate thing to do or should I be opening a new issue and linking to this thread?

**Comment by jzf2101** [comment]
I'd create a new issue

**Comment by willingc** [comment]
Yes. New issue would be best @Ruv7.

**Pull request merged**
