### PR TITLE
Add /try to the nav

### PR DESCRIPTION
**Pull request by palewire**
It is a bit unusual the /try page isn't in the nav. It seems to me like perhaps the first place you might want a newbie to find.

Is there a reason it isn't there now? I propose we add it as part of the gradual cleanup sparked by the discussion in #433 and as a companion to #497.

### CODE REVIEW

**Comment by choldgraf** [comment]
I think this is a reasonable change, with two caveats:

1. (minor) We've already got a lot of nav links in the top navbar, so I worry we're starting to clutter it up a bit
2. (major) We have #513 still unresolved, and try is generating a *ton* of traffic to mybinder.org already that is generating a high cost. It would be really nice if we had a resolution to this before making `try` even *more* prominent

**Comment by palewire** [comment]
Makes sense. Another argument to merge #497 and combine the events and get involved pages per #499. You agree?

**Comment by choldgraf** [comment]
Yep that sounds reasonable to me!

**Comment by choldgraf** [comment]
Though for some of these, I think we should point people to the jupyter-wide docs at jupyter.readthedocs.io. those are a bit more in depth and more like proper documentation, while jupyter.org is more like a brochure site (at least I think that is how they relate to one another, they both predate me!)

**Comment by palewire** [comment]
Alrighty. I'll get around to merging Events and Get Involved before too long. Along those same lines, there is an open pull request now to switch Documenation nav to just such a link off. https://github.com/jupyter/jupyter.github.io/pull/507

**Review by Carreau — APPROVED** [review]

**Comment by Carreau** [comment]
Ok, let's try.

**Comment by Carreau** [comment]
pun was not intended.

**Pull request merged**
