### PR TITLE
Add travis and linters

### PR DESCRIPTION
**Pull request by willingc**
This adds travis support and ~~[nu.validator](https://github.com/svenkreiss/html5validator)~~.

Will check the master branch

### CODE REVIEW

**Comment by willingc** [comment]
@Carreau This adds travis support to check for a clean Jekyll build, runs [html-proofer](https://github.com/gjtorikian/html-proofer), and [csslint](https://github.com/CSSLint/csslint). Travis build fails due to some HTML and CSS errors.

**Comment by Carreau** [comment]
Thanks @willingc !

You can tell the Travis matrix that some things are actually [allowed to fail](https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail) hence you get travis runnign and can slowly catch up with the backlog, until it passes, and they you stop allowing them to fail :-)

**Comment by Carreau** [comment]
I see you are pushing many commits, do you need a hand ?

**Comment by willingc** [comment]
@Carreau Sure! If you can get the allowed_failure to work reliably with htmlproofer that would be great.

**Pull request merged**
