### PR TITLE
Resetting the logo-nav CSS changed by the widgets on the widgets page

### PR DESCRIPTION
**Pull request by woswos**
## References
#364 CSS related bugs in the widgets page

## Changes
The original navigation bar that is uniform across the website is given below:
Screen Shot 2020-05-11 at 12 01 00 AM

However, the externally loaded widgets overwrittes some of the CSS class settings set by the `logo-nav.css` file and the navigation bar and the footer breaks:

Screen Shot 2020-05-10 at 11 59 52 PM

I solved this issue by loading the `logo-nav.css` again at the end of this page:

Screen Shot 2020-05-10 at 11 58 25 PM

This update doesn't break other parts of the website based on my tests.

### CODE REVIEW

**Comment by choldgraf** [comment]
Huh - the JS on this page doesn't actually work for me, so it is hard to know if this fixes things :-)  but it seems reasonable and definitely possible that the widget code updates the CSS somehow. @jasongrout do you know which widgets might override the CSS of the jupyter logo?

**Comment by choldgraf** [comment]
Once you get #367 merged in can you rebase so we can take another look at this?

**Comment by blink1073** [comment]
@woswos, #367 is merged, are you available to rebase and check again?

**Comment by willingc** [comment]
Hi @woswos, Do you wish to follow up on this PR? Thanks!

**Comment by woswos** [comment]
I totally forgot about this, thank you for the reminder. I will look into it.

**Comment by woswos** [comment]
@willingc please let me know if this solved the issue or if I messed up even more. I tried rebasing from the master branch.

**Comment by willingc** [comment]
HI @woswos, It looks like your rebase applied all the old commits. I think that you only wanted commit `6b2bc2b` in this PR and your rebase pulled into old history.

If you have your git remotes set to your fork as origin and this jupyter repo as upstream, try:

```
git fetch upstream
git rebase upstream/master
git push - f origin widgets-page-fix
```

**Comment by woswos** [comment]
I'm closing this since I created a new clean PR, thanks everyone!

**Pull request closed without merging**
