### PR TITLE
Added BeakerX Logo to home page, removed one of the outdated PERL logos

### PR DESCRIPTION
**Pull request by tgeorgeux**
It was brought to my attention that we didn't have BeakerX represented on the hero image with many Kernel-Related images. When working to fit it in I noticed PERL was represented twice, temporarily switched PERL Onion logo with BeakerX logo until I have time to re-do the entire hero image.

### CODE REVIEW

**Comment by zmughal** [comment]
Hello!

I'm the IPerl language kernel developer. I just wanted to note that the Camelia butterfly is only associated with Perl 6 while the Onion represents the various Perl languages, but I chose it to represent the kernel for Perl 5. These are different languages and there are two different language kernels.

**Comment by tgeorgeux** [comment]
Ah thank you so much for the update! I wish I had asked you when I was trying to figure out what both of those represented. If I had room for one of PERL logos on the main page right now, which of the three (onion, camel, or butterfly) would you prefer/suggest?

**Comment by tgeorgeux** [comment]
Forgot to submit my description of the PR @zmughal, I hope this adds a little more context. 😄

**Comment by zmughal** [comment]
I think the Onion would represent all of them, but I can't speak for the rest of the Perl community. Here is some more information:

- <https://en.wikipedia.org/wiki/Perl#Onion_symbol>.
- <https://github.com/dnmfarrell/Perl-Icons>.

I chose the Onion because it has explicit permission to be used to represent Perl or products that use Perl by both commercial and non-commercial entities.

**Comment by shadowcat-mst** [comment]
Ideally, you'd either use just the onion, or if there are perl5 and perl6 kernels, the perl5 raptor plus the perl6 butterfly

**Comment by ellisonbg** [comment]
Can you paste a screenshot of the final?

**Comment by afshin** [comment]
@tgeorgeux The `circle3.svg` image needs to have the width and height in it like it had before: `width="747px" height="313px"`. This PR **currently** renders like this:

before

But after adding the `height` and `width`, it renders like this:

after

cc: @ellisonbg

**Comment by afshin** [comment]
Here's the `diff` between what is currently in this PR and adding the width/height:

```diff
diff --git a/assets/circle3.svg b/assets/circle3.svg
index 231845c..af903ef 100644
--- a/assets/circle3.svg
+++ b/assets/circle3.svg
@@ -1,7 +1,7 @@
 <?xml version="1.0" encoding="utf-8"?>
 <!-- Generator: Adobe Illustrator 22.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
 <svg version="1.1" id="Layer_1" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns"
-        xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 747 313"
+        xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="747px" height="313px" viewBox="0 0 747 313"
         style="enable-background:new 0 0 747 313;" xml:space="preserve">
 <style type="text/css">
        .st0{opacity:9.000000e-02;fill:#767474;enable-background:new    ;}
```

**Comment by SylvainCorlay** [comment]
This looks good to me!

**Comment by SylvainCorlay** [comment]
Would be nice to replace the "C++" text with the actual C++ logo https://github.com/isocpp/logos/blob/master/cpp_logo.svg.

**Comment by SylvainCorlay** [comment]
Merging !!! Woot!

**Comment by scottdraves** [comment]
🐬 🐬 
thank you!

**Comment by tgeorgeux** [comment]
Special thanks to @i-am-am for quickly iterating on the visual design for me on this.

**Pull request merged**
