### PR TITLE
Rework the footer with link lists

### LINKED ISSUE #601: Expand the footer to include two link lists, one for nav items and a second for project pages
Per the discussion in #529, the footer should be expanded to include two link lists, one for nav items and a second for project pages. How so is up for debate. The work to resolve this issue could, optionally, try to tackle the problems raised in #587.

### PR DESCRIPTION
**Pull request by palewire**
This fixes #601. 

Before:
Screenshot from 2022-01-09 07-23-37

After:
Screenshot from 2022-01-09 07-23-58

### CODE REVIEW

**Review by choldgraf — COMMENTED** [review]
The code changes look good to me - for style, what do you think about centering this 3-column list of projects, so there's not so much whitespace to the right, and so it follows page content structure more closely?

**Comment by palewire** [comment]
The trick there is that they will lose their shared left alignment with the logo and copyright text at the bottom. I suspect the happy medium would be some kind of max width set on all content on the footer that would prevent it from leaving a lot of space to the right on large device widths. However, considering the rest of the page design there's not an obvious value to set that at.

I could go with the "content--wide" width now set for art on the interior pages.

**Comment by choldgraf** [comment]
Good point - your proposed solution sounds good to me!

**Comment by palewire** [comment]
The max width is in. Here's what you see now.

Screenshot from 2022-01-09 11-12-18

Screenshot from 2022-01-09 11-12-30

**Comment by krassowski** [comment]
For the lower part, could we use white text color? C-f https://github.com/jupyter/jupyter.github.io/issues/587

**Comment by choldgraf** [comment]
+1 from me - it does makes sense that white would be more accessible

**Comment by choldgraf** [comment]
@palewire what do you think about the proposal to have white text in the footer?

**Comment by palewire** [comment]
Was hoping to put in sometime mocking up alternatives and then getting them tested, not just by Lighthouse, but also by the alternative standard mentioned in the issue. I haven't made time for that yet. My hope would be that with a little experimentation we could use that method settle on one color that would work in both sections of the footer, just for consistency's sake. Maybe I'm overthinking it.

**Comment by choldgraf** [comment]
sounds good - no hurry, just wanted to make sure you saw the conversation. Want to do that before finishing this PR? Or open an issue to focus on the footer color and add it to the milestone?

**Comment by palewire** [comment]
I'm okay either way. I just want to make sure we ultimately nail down a solid approach we can point to standards with. That can be now, or it can be later.

**Comment by choldgraf** [comment]
@krassowski would you mind if we tracked the footer text color in a dedicated issue? I think the addition of the links here is a nice addition, so I'm inclined to move forward in the name of iterative progress, but what do you think?

**Comment by krassowski** [comment]
I'm fine with that :). I would suggest a rebase/merge of master before merging into matter to double check that validator and links check passes.

**Comment by palewire** [comment]
Master is rebased

**Review by choldgraf — APPROVED** [review]
Awesome - thanks for this improvement!

**Comment by choldgraf** [comment]
hmmm the footer link list seems a bit wonky:

image

**Comment by choldgraf** [comment]
(note that I didn't see this in the PR preview, not sure why the behavior is different)

**Comment by palewire** [comment]
I suspect this is a caching issue that will resolve once the TTL expires. But I could be wrong.

**Comment by choldgraf** [comment]
yep you're right, it's fixed now

**Pull request merged**
