### PR TITLE
Cut cfp option in index.html frontmatter

### PR DESCRIPTION
**Pull request by palewire**
I believe this has been deprecated.

### CODE REVIEW

**Comment by choldgraf** [comment]
any idea what this means?

**Comment by palewire** [comment]
Nope. Some past "call for papers?"

**Comment by slel** [comment]
That was a "call for proposals" for JupyterCon 2018 in NYC.

https://github.com/jupyter/jupyter.github.io/pull/262
https://github.com/jupyter/jupyter.github.io/commit/89cf090766e88a5f3ea7296cbd82c0569aa8acad

**Comment by palewire** [comment]
Sounds like something that can be cut then.

**Review by choldgraf — APPROVED** [review]
let's cut it - can be added back later easily if need be 👍

**Pull request merged**
