### PR TITLE
fixes issue #52: added hover to buttons

### PR DESCRIPTION
**Pull request by go-bears**
added hover feature to paypal button on donate page and main page buttons under Jupyter architecture section

(fixes issue #52)

### CODE REVIEW

**Comment by Carreau** [comment]
Thanks  a lot @go-bears !

I think we might want the same style than on the index page ie  `background-color: #DB5106;` on hover more than a deep blue.

Though @ellisonbg / @cameronoelsen  ? (style of this PR on hover)

screen shot 2016-01-12 at 09 19 13

@go-bears You do not need to close the PR to update it (I saw you submitted #68) you can just push extra commit on the same branch, and the PR will be updated. You can also force push if you want to completely or rewrite history. I don't go into details here, but feel free to ask question if you are not sure of how to push/force push or use git or something else.

**Comment by go-bears** [comment]
thanks  @Carreau for the color reference! will get to it now.

**Comment by Carreau** [comment]
Better ! I think the drop shadow is still blue :-) 

screen shot 2016-01-13 at 08 40 40

**Comment by go-bears** [comment]
Hi @Carreau I think finally all the button issues are fixed for now.  Thank you for your guidance!

**Pull request merged**
