### PR TITLE
Tidy up Try page

### PR DESCRIPTION
**Pull request by palewire**
This path tidies up the content of the Try page. It does the following:
- Slims down the headline
- Moves the external links down into an intro paragraph
- Reorders the first three boxes to mirror the order of homepage modules
- Reorders the remaining boxes alphabetically
- Trims down the box language to be more consistent across items

Before:
Screenshot from 2022-01-08 07-11-48

After:
Screenshot from 2022-01-08 07-11-57

### CODE REVIEW

**Comment by palewire** [comment]
My lingering concern here is that nothing on the page makes clear that the first two Jupyter boxes are going to drop you into a Python environment. As a long-time user, I'm familiar with the fact that Python is, in some vague sense, the default programming language. In trying to look at this page with fresh eyes, I'm not sure that would be clear to a newbie who lands on it today.

**Comment by choldgraf** [comment]
I think the language / structure cleanup is nice 👍 

regarding your concern - I agree...maybe one issue is there there are three different kinds of things demonstrated here:

- Jupyter interfaces (Lab, Notebook, Voila), which is more about the interface itself rather than any specific language
- The concept of a Jupyter Notebook in general, which is more about the document structure, metadata, etc
- The idea of language-agnosticity, and experiences in a variety of languages

Maybe some of the confusion is that we are lumping all of these into a single list of links, and thus cannot set different expectations for each as cleanly?

**Comment by palewire** [comment]
We could break it into two lists. One that is products, and the chatter could emphasize they will use python. The second list could have an intro explaining it contains examples of other programming languages.

**Comment by choldgraf** [comment]
@palewire what do you think about the changes proposed here in this PR to your branch? https://github.com/jupyter/jupyter.github.io/pull/612 ?

**Comment by palewire** [comment]
Love it

**Comment by choldgraf** [comment]
I think that looks pretty good! Maybe we need an `h2` header "Jupyter Products" and "Jupyter Kernels" for each section?

**Comment by palewire** [comment]
Those are in.

Screenshot from 2022-01-09 11-16-09

**Comment by krassowski** [comment]
Suggestion on wording: what do you think about "Applications" in favour of "Products"?

**Comment by choldgraf** [comment]
I'm fine with either 🤷

**Comment by palewire** [comment]
I defer to people with more experience with marketing the project here.

**Review by choldgraf — APPROVED** [review]
Alrighty let's just go with applications then - I made a commit to update the PR

**Comment by palewire** [comment]
Oops. We may have lost the h2's there. I can patch.

**Pull request merged**
