### PR TITLE
NASA color fix

### PR DESCRIPTION
**Pull request by cameronoelsen**
-Changed the NASA logo in the users section on the front:
—Now uses three shades of gray to make more distinguishable and readable
—Changed the height from 60 to 70 to match the size of other logos
surrounding it

### CODE REVIEW

**Comment by cameronoelsen** [comment]
I am using: #B1B1B1 for the color of the circle, #DDDDDD in substitution for the red and white for the other elements if anyone wanted to reference this!

**Comment by ehsteve** [comment]
Looks great!

**Comment by ellisonbg** [comment]
Thanks, it looks great, merging!

On Thu, Oct 29, 2015 at 1:26 PM, Steven Christe <notifications@github.com>
wrote:

> Looks great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/pull/63#issuecomment-152256793>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by rgbkrk** [comment]
:+1:

**Pull request merged**
