### PR TITLE
Create widget showcase gallery

### PR DESCRIPTION
**Pull request by SylvainCorlay**
This is an initial implementation of a widget showcase gallery for the jupyter.org website.

screencast-jupyter-org

See test page: http://sylvaincorlay.github.io/widgets.html

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@fperez we discussed this in San Francisco last month.

**Comment by ellisonbg** [comment]
Fantastic! I would like to user test this. Could you write up a vert short description on this PR of:

* When a user gets to this page, what are they trying to do? What is their motivation, or end goal?
* A short list of tasks that I can give to a user (non-technical) related to this page that I can have a user perform (while being recorded) and a set of questions they can answer while their perform those tasks.

Here is a short example:

Goal: 

A user doesn't know what our widgets are, and they are trying to find out what they are.

Tasks:

1. Go to the jupyter.org home page and find the page about widgets.
2. Read the page and describe what widget are.
3. Based on this page, in what situations would you use widgets?
4. What is the leaftlet widget for?
5. If you wanted to use widgets, what would be your next step?

Once we have this information, I propose we merge and then I can perform the tests and post the results. Then iterate...

Also @cameronoelsen at some point, it would be great if you could take a design pass at this page.

**Comment by SylvainCorlay** [comment]
Good idea to user test it!
It still certainly lacks some narrative text in each section (hence the "WIP").

**Comment by SylvainCorlay** [comment]
From a user experience perspective, there are multiple links in the navbar that send the user outside of the jupyter.org website.

Both DOCUMENTATION and INSTALL go to the readthedocs documentation. Until we come up with a better way to embed this inline, I propose we remove those links from the navbar and add them to the front-page... The expectation is that the navbar items are not external links.

The NBVIEWER and BLOG items point to subdomains.We could handle this case separately...

**Comment by SylvainCorlay** [comment]
cc @jdfreder

**Comment by SylvainCorlay** [comment]
This seems to work well in chrome, firefox, safari, and ubuntu web browsers. Anyone who owns a windows computer can try to build it locally to try on IE.

**Comment by SylvainCorlay** [comment]
Works with IE. Had to add a workaround for a IE11 svg scaling bug. (I truly hate IE.)

**Comment by zhaehn** [comment]
Typo in the ipyleaflet section.  After clicking on ipyleaflet on the left, the title in the middle reads "ipyleafet" - missing an L.

**Comment by SylvainCorlay** [comment]
Fixed typo.

**Comment by Carreau** [comment]
`Reset` Icon is confusing, I would use "home" or smth else.
`Save` Icon is confusing, I would use `Download`/`Down Arrow` .

**Comment by Carreau** [comment]
Could the treejs be a Jupyter logo, or a sphere of Jupiter ?

**Comment by SylvainCorlay** [comment]
> Reset Icon is confusing, I would use "home" or smth else.
> Save Icon is confusing, I would use Download/Down Arrow .

This is a bqplot issue. Want to open the issue in bqplot?

**Comment by SylvainCorlay** [comment]
> Could the treejs be a Jupyter logo, or a sphere of Jupiter ?

Jupiter ? ;)

**Comment by Carreau** [comment]
> Jupiter ? ;)

Yes, the planet, with the red spot. And [Moooons](https://xkcd.com/1300/).

**Comment by ellisonbg** [comment]
Attempting a Problem Statement for this page:

I am: user of the Jupyter Notebook
I am trying to: [outcome/job]
But: [problem/barrier]
Because: [root cause]
Which makes me feel: [emotions]

**Comment by SylvainCorlay** [comment]
Why did you close the PR?

**Comment by jasongrout** [comment]
I am: *prospective* user of Jupyter Notebook
I am trying to : compare it to Rstudio and other widget frameworks
But: I have to become a user to see what this widget thing is
Because: we don't have an easy way to quickly see what widgets are outside of the notebook
Which makes me feel: 😢 (until I find this page, then I feel 😀 🎆 🍰 )

**Comment by SylvainCorlay** [comment]
> Which makes me feel: sad :cry: (until I find this page, then I feel happy :grinning: :fireworks: :cake: )

:100:

**Comment by ellisonbg** [comment]
Ooops did t mean to

**Comment by ellisonbg** [comment]
@jasongrout - thanks the persona helps. I think that we should probably address the questions uses will have about comparing this to RStudio, Shiny, etc.

**Comment by ellisonbg** [comment]
@SylvainCorlay is this PR in a good enough state that we could deploy it, run user tests and iterate? I can run the user tests quickly.

**Comment by Carreau** [comment]
It would just be nice to know (document) how highlight.css has been generated. 

And likely figure out  a way how reduce the html in the widget page, though I agree that in **this** case it can be quite hard. 

Might be possible to wrap in `{% markdown %}{% end%}` tags, but I'm fine if this is added on the 
Technical Dept sheet and opened as separate issues.

**Comment by Carreau** [comment]
https://sylvaincorlay.github.io/bqplot.js  is 404 on your fork.

**Comment by Carreau** [comment]
> https://sylvaincorlay.github.io/bqplot.js is 404 on your fork.

Wait, no, require says its 404 but it's probably a search path, as the graph works. 

Unrelated, on the Home page the "Widget" card should link to this new page. 

@ellisonbg might want to enable typekit on your fork for testing. 

I'm regularly confuse on the website and search the "Home" link in the nav bar, which is the Logo, but it is not "obvious", my brain often take a second or 2 to figure that out.

**Comment by SylvainCorlay** [comment]
> https://sylvaincorlay.github.io/bqplot.js is 404 on your fork.

Yeah these are search paths indeed.

> how reduce the html in the widget page

In the template file itself, there is really little. The *generate* html is long because the json is inline.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay is this PR in a good enough state that we could deploy it, run user tests and iterate? I can run the user tests quickly.

I think that it is ok. It may require a more recent version of browsers than the rest of the website...

**Comment by SylvainCorlay** [comment]
> Unrelated, on the Home page the "Widget" card should link to this new page.

Yes, but I would make it a separate PR, making each one of the cards a link.

**Comment by SylvainCorlay** [comment]
Merge?

**Comment by ellisonbg** [comment]
Yes!

On Fri, Jun 3, 2016 at 8:07 AM, Sylvain Corlay <notifications@github.com>
wrote:

> Merge?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/pull/93#issuecomment-223605012>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0BjY0S0uRwGdpThZyMBYAjvcpOSjks5qIEMugaJpZM4IpN4e>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
I"ll assume Brian is on his phone and cannot press the merge button so I'll do it for him.

**Comment by fperez** [comment]
Thanks so much @SylvainCorlay for pushing on this, and everyone else! I've really, really wanted this for a long time :)

**Pull request merged**
