### PR TITLE
Affiliation changes

### PR DESCRIPTION
**Pull request by jasongrout**
This PR includes several affiliation changes for the website.

See also https://github.com/jupyter/governance/pull/120

### CODE REVIEW

**Review by Carreau — APPROVED** [review]

**Comment by damianavila** [comment]
This also needs updates on the https://github.com/jupyter/jupyter.github.io/blob/master/_includes/partners.html
Adding some new logos, right?

**Comment by damianavila** [comment]
Btw, I also need to update my affiliation here...

**Comment by jasongrout** [comment]
> Adding some new logos, right?

Done for me. @blink1073 - do you want to add a logo in this PR?

**Comment by blink1073** [comment]
>  @blink1073 - do you want to add a logo in this PR?

Thanks, I added one

**Comment by damianavila** [comment]
@jasongrout, I opened a PR against your branch with some more updates 😉  .

**Comment by jasongrout** [comment]
> @jasongrout, I opened a PR against your branch with some more updates 😉 .

Thanks. I merged those in.

**Comment by jasongrout** [comment]
@willingc @rgbkrk @ivanov - Do you want to add a Noteable logo?

**Comment by jasongrout** [comment]
@parente - do you want to add a Thorn logo?

**Comment by jasongrout** [comment]
Moving to "ready for review" and merging. @willingc @rgbkrk @ivanov or @parente - if you want to add the logo for your employers, still please feel free to do on this PR or on a new one.

**Comment by willingc** [comment]
Thanks @jasongrout. Will add in a separate PR. Feel free to merge this.

**Comment by damianavila** [comment]
@jasongrout I have a PR against your branch with an updated logo here: https://github.com/jasongrout/jupyter.github.io/pull/3

Thanks!!

**Comment by jasongrout** [comment]
Merged. Thanks everyone!

**Pull request merged**
