### PR TITLE
Add /governance to the nav. Delete /conduct

### PR DESCRIPTION
**Pull request by palewire**
Reflecting on #529, this page seems like one of the strongest candidates to add to the nav. It fits my rough qualification by being true "metadata" about the overarching project. It has been recently updated. It doesn't compete with technical documentation available elsewhere. So I nominate that we add it.

### CODE REVIEW

**Comment by choldgraf** [comment]
Hmm - my understanding was that the CoC lived here: https://jupyter.org/governance/conduct/code_of_conduct.html

We should make sure it is clear which one is the source of truth.

**Comment by palewire** [comment]
Ah. I was unaware of this other page. Why have both?

**Comment by palewire** [comment]
One solution I can imagine is deleting the page in this repo and using the nav to link to that governance page.

**Comment by choldgraf** [comment]
> Ah. I was unaware of this other page. Why have both?

Mostly I think it is a lack of coordination and losing institutional memory over time as folks have moved on.

It looks like the CoC sections in https://github.com/jupyter/governance/tree/master/conduct cover more territory, and have been updated a bit more frequently in general. E.g. [this PR was a pretty hotly debated one](https://github.com/jupyter/governance/pull/56) and it was made to the jupyter/governance repo instead of here.

How about we add a `governance` top-level item, that is an external link to `jupyter.org/governance`. That would include the CoC as well.

**Comment by palewire** [comment]
Sounds good to me. I'll rework this request to fit that bill.

**Comment by palewire** [comment]
That's done, @choldgraf

**Comment by krassowski** [comment]
Could we add a redirect so that the `/conduct` premalink redirects to https://jupyter.org/governance/conduct/code_of_conduct.html - just because there may be other repositories and old documentation pages linking to it?

**Comment by slel** [comment]
Good point, that came up recently (2022-09), see #414 #415.

**Comment by palewire** [comment]
@krassowski and @slel, the redirect is in.

**Review by krassowski — APPROVED** [review]
That's great, thank you!

**Pull request merged**
