### PR TITLE
Added NASA to list of users

### PR DESCRIPTION
**Pull request by ehsteve**

### CODE REVIEW

**Comment by rgbkrk** [comment]
:shipit: Thanks!

**Comment by minrk** [comment]
This is awesome. But do we need official permission to use the logo?

**Comment by slel** [comment]
... and is it possible to use a grayscale logo?

**Comment by ellisonbg** [comment]
Yes, please use a grey scale logo that matches the grey of the other logos
on the page. Also, we do need to get some sort of semi-official permission
- that can provided on this PR.

On Thu, Oct 29, 2015 at 9:13 AM, Samuel Lelièvre <notifications@github.com>
wrote:

> ... and is it possible to use a grayscale logo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/pull/61#issuecomment-152175517>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
