### PR TITLE
NumFOCUS -> LF Charities changes

### PR DESCRIPTION
**Pull request by jasongrout**
These changes update our website to reflect our new home at LF Charities.

### CODE REVIEW

**Comment by jasongrout** [comment]
@Carreau - it seems the netlify handler is having issues: https://app.netlify.com/sites/jupyter-github-io/deploys/671193d6a2b3c700089590c0

Is that handler under your account? It says "[Matthias Bussonnier's team/jupyter-github-io](https://app.netlify.com/sites/jupyter-github-io/deploys)"

**Comment by jasongrout** [comment]
Our netlify preview seems to have problems right now, but here is the donate box at the bottom of jupyter.org/about after this PR:

image

**Comment by Carreau** [comment]
Hum here is the error, 
```
An error occurred while installing bigdecimal (3.1.8), and Bundler cannot
continue.

In Gemfile:
  github-pages was resolved to 232, which depends on
    jekyll-mentions was resolved to 1.6.0, which depends on
      html-pipeline was resolved to 2.14.3, which depends on
        activesupport was resolved to 7.2.1.1, which depends on
          bigdecimal
Error during gem install
```

Let me know if you need someone to be added to the team, but I think on free plan I'm already at the limit.

**Comment by Carreau** [comment]
Well I tried a random change and it appear that worked... 

Anyway, I don't think nettlify really support ruby officially, so maybe we should move to a github action, IDK.

**Review by Carreau — APPROVED** [review]

**Review by Zsailer — APPROVED** [review]

**Review by fperez — APPROVED** [review]
I approve the content changes of the PR. I see some failures still in CI, though the PR addresses already a few issues.

As long as those failures can be ignored for the site to build, I say 🚀 .  Thanks @jasongrout !

**Comment by jasongrout** [comment]
I just reran the failing checks and they passed. I think we are good on that front.

**Pull request merged**
