### PR TITLE
Refactored container for simplicity

### PR DESCRIPTION
**Pull request by palewire**
This pull request replaces the container logic of bootstrap, and our numerous hacks on top of it, with a less complex system. Pages should look virtually the same afterward. 

Here's what it does:
- Creates a new _containers component
- Adds a new set of content classes that handle max-width separately from the container
- Reduces the max-width for text blocks to a narrower, more readable extent in line with mainstream publishers
- Removes numerous negative margin and padding hacks
- Removes unused page_content type classes
- Switched the About page to an HTML template to make it work and to tee up future refactoring

### CODE REVIEW

**Comment by choldgraf** [comment]
This sounds great to ke - my main question is what logic we are losing from the bootstrap helper class. I guess there was just a bunch of stuff we weren't using?

Also we should totally do something like this for the jupyter book and pydata sphinx themes...

**Comment by palewire** [comment]
The bootstrap container used a media query to set different max widths for all content at different viewports. Instead, I've defined two fixed max widths, a narrower one for copy and a wider one for art. Both will fill 100% at mobile devices. Pretty subtle, but helps make the code more declarative and consistent.

**Comment by palewire** [comment]
This will fix #541

**Review by choldgraf — APPROVED** [review]
sorry for the slow turnaround, was traveling back to California

This looks good to me - I like that we are simplifying our CSS and HTML a bit, removing unnecessary rules and also removing dependencies on Bootstrap. The new width for copy sounds reasonable to me, I think it's a nice improvement.

@palewire I see you've been pushing more updates to this PR, is there something else you want to finish up or is this good to go?

**Comment by palewire** [comment]
It's good to go. I just killed some cruft.

**Pull request merged**
