### PR TITLE
[WIP] Build website with Jekyll

### PR DESCRIPTION
**Pull request by Carreau**
it almost works, see the current diff of the HTML [here](https://github.com/Carreau/jupyter.github.io/commit/1a438e694f44c9fabd3c02c1489b6af22ac19f6b) for now. 

The only think which is missing is having the current page being highlighted and not clickable in the navbar. Advantage is that Header and Footer (and a few other things) are in only 1 place for the all website, which will be **much** nicer for update. 

Wi a bit of word we can also just drop a markdown file somewhere to create a new page. 

(I'll rebase and remove `_site` once this is ready)

### CODE REVIEW

**Comment by rgbkrk** [comment]
Very happy about templating if it remains consistent here. :+1:

**Comment by Carreau** [comment]
Builds on my GitHub pages: http://carreau.github.io/jupyter.github.io/.

Already happy about templating and having fixes in 1 place.

**Comment by ellisonbg** [comment]
Great, but there are some visual style differences:

* Current page is not highlighted in orange in nav bar.
* Vertical position of main logo on home page is different.

**Comment by ellisonbg** [comment]
Can you add a README.md with instructions on how to install the needed dependencies and rebuild the site - focused on designers who don't code?

**Comment by ellisonbg** [comment]
I am +1 on this though.

**Comment by ellisonbg** [comment]
Although I would probably prefer to do this type of thing in with node.js - but not a big deal

**Comment by Carreau** [comment]
The point of using Jekyll is the build step is done **by github**. There is no step needed to recompile the website. It **is** what powers github pages. I'm working on Fixing the toolbar/orangy thing.

Regarding node by curiosity, what would you use ?

Envoyé de mon iPhone

**Comment by Carreau** [comment]
@ellisonbg can you give a look at http://carreau.github.io/jupyter.github.io/ again ? All should be fixed.

Differences are : 

Footer  `About`->`Project` (to match NavBar) + Build date.

Rest should be identical. 

Note **do not merge yet** will not build if merged, there is a custom option in order for it to build on **my fork**.

**Comment by ellisonbg** [comment]
Looks good, I would go ahead with things.

On Wed, Oct 21, 2015 at 12:55 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> can you give a look at
> http://carreau.github.io/jupyter.github.io/ again ? All should be fixed.
>
> Differences are :
>
> Footer About->Project (to match NavBar) + Build date.
>
> Rest should be identical.
>
> Note *do not merge yet* will not build if merged, there is a custom
> option in order for it to build on *my fork*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/pull/50#issuecomment-149783001>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
rebased; cleaned; squashed; updated.

Should be ready for merge.

**Pull request merged**
