### PR TITLE
Add menbers and pictures

### PR DESCRIPTION
**Pull request by Carreau**
Add @blink1073 (now I can remember the number) and @willingc  on the website, fix the html, add pictures of people, because we are people, not numbers or avatars. And change the number of steering member to 14.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Screenshot?

**Comment by blink1073** [comment]
Looks like it is mis-rendering: http://jupyter.org/about.html

**Comment by SylvainCorlay** [comment]
Reload!

**Comment by SylvainCorlay** [comment]
Jekyll takes some time to reflect css changes.

**Comment by takluyver** [comment]
Not convinced by the sepia tinted images :neutral_face:

**Comment by Carreau** [comment]
> Not convinced by the sepia tinted images 😐

Pr welcome.

**Comment by SylvainCorlay** [comment]
black & white would solve the issue of different lightnings between pictures.

**Comment by Carreau** [comment]
> black & white would solve the issue of different lightnings between pictures.

No, It was originally B&W (locally) and was looking weird.

**Comment by SylvainCorlay** [comment]
ok

**Comment by blink1073** [comment]
Confirmed that it renders properly now, thanks!

**Comment by takluyver** [comment]
#159 removes the sepia filter.

**Comment by parente** [comment]
Oh dang. Now I need a real picture as my avatar.

**Comment by willingc** [comment]
@parente I kind of like the dinosaur ;-)

**Comment by parente** [comment]
Agreed. This bald guy pic is boring in comparison. But now no one on the internet will know that I'm really a lightsaber wielding dinosaur.

**Comment by Carreau** [comment]
I honestly like the dinosaur, it show that we are human (sic), and all
clones with same mindset and priorities. Also you look good for a 60 M
years old fossil.

**Pull request merged**
