### PR TITLE
Add 2023 JDC Cohort

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Review by JasonWeill — APPROVED** [review]
Looks good, although I notice that the "deploy preview" workflow isn't working, because of a problem with dependencies.

**Comment by SylvainCorlay** [comment]
The latest version of jekyll stops bundling some deps and requires the corresponding gems instead. These gems require Ruby 3. We need to update the build image on netlify so that it has Ruby 3.

**Comment by SylvainCorlay** [comment]
I temporarily pinned jekyll for the netlify preview to fix the build. Will open a separate issue on this.

**Review by trungleduc — APPROVED** [review]

**Review by afshin — APPROVED** [review]
Thank you @SylvainCorlay!

**Pull request merged**
